config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index", as: :xindex
  get "tasks/new", to: "tasks#new", as: :new
  get "tasks/:id", to: "tasks#show", as: :show
  post "tasks", to: "tasks#create", as: :tasks
  get "tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update", as: :update
  delete "tasks/:id", to: "tasks#destroy", as: :task_delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    #generate a new task object to send to view
    #(DO NOT MAKE IT PRESISTANT)
    @task = Task.new
  end

  def create
    #genrate a Task new and populate it with strong params
    #make it presistant
    @task = Task.new(task_params)
    if @task.save
      redirect_to show_path(@task)
    else
      redirect_to index_path
    end
  end

  def edit
    @task = Task.find(params[:id])
    # We'll see that in a moment.
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    if @task.save
      redirect_to show_path(@task)
    else
      redirect_to index_path
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to index_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if current_page?(new_path) %>
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<% else %>
<%= form_for @task, url: update_path(@task), method: :patch do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :completed %>
    <%= f.check_box :completed, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<% end %>


<!-- def form_for (arg)
  if arg.id == nil?
    #make path to post of argument (create route)
  else
    #make PATCH to the update route
  end
end -->

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>All the tasks</h1>

<% @tasks.each do |task| %>
  <h3><%= check_box_tag '[]', task.completed %>
  <%= link_to task.title, show_path(task)%><%= link_to 'Remove task', task_delete_path(task), method: :delete%></h3>
<% end %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>